LightStoneControlType = {
  Main = 1,
  Sub0 = 2,
  Sub1 = 3,
  Cron = 4
}
PaGlobal_SpiritEnchant_All = {
  _ui = {
    stc_titleBg = nil,
    stc_mainTabBg = nil,
    btn_mainRadio = {
      [1] = nil,
      [2] = nil,
      [3] = nil
    },
    stc_selectBar = nil,
    stc_line = nil
  },
  _ui_enchant = {
    stc_enchantBg = nil,
    stc_imageArea = nil,
    stc_resultNak = nil,
    stc_noticeBar = nil,
    stc_image = nil,
    stc_wingCenter = nil,
    stc_wingTop = nil,
    stc_wingBottom = nil,
    stc_wingsInfo = {
      [1] = {slot = nil, count = nil},
      [2] = {slot = nil, count = nil},
      [3] = {slot = nil, count = nil}
    },
    txt_enchantRate = nil,
    stc_blackSpiritCount = nil,
    progress2_1 = nil,
    txt_count = nil,
    stc_equipSlot = nil,
    stc_image2 = nil,
    stc_caphrasImage = nil,
    stc_caphrasEquipSlot = nil,
    stc_caphrasCurEquipSlot = nil,
    stc_caphrasSlot = nil,
    txt_caphrasCount = nil,
    progress_caphrasNextExp = nil,
    progress_caphrasCurExp = nil,
    stc_caphrasRightLine = nil,
    stc_caphrasLeftLine = nil,
    stc_caphrasLeftWing = nil,
    txt_caphrasNextStep = nil,
    txt_caphrasNextMaterialInfo = nil,
    txt_caphrasStatusTitleL = {},
    txt_caphrasStatusValueL = {},
    stc_caphrasRightWing = nil,
    txt_caphrasCurStep = nil,
    txt_caphrasEffect = nil,
    txt_caphrasStatusTitleR = {},
    txt_caphrasStatusValueR = {},
    stc_blablaBg = nil,
    txt_blablaText = nil,
    stc_infoArea = nil,
    stc_bg = nil,
    txt_subTitle = nil,
    txt_subTitleValue = nil,
    txt_valks = nil,
    txt_valksValue = nil,
    txt_plus = nil,
    txt_plusValue = nil,
    btn_Add = nil,
    stc_line = nil,
    stc_blackSpiritCountBG = nil,
    stc_buttonArea = nil,
    radio_enchantNormal = nil,
    radio_enchantPerfect = nil,
    chk_enchantForce = nil,
    chk_enchantCron = nil,
    chk_enchantDefenceFail = nil,
    btn_stackChange = nil,
    txt_stackCoolTime = nil,
    txt_enchantDesc = nil,
    chk_skipAni = nil,
    txt_maxEncahnt = nil,
    stc_tubalaExchangeBg = nil,
    txt_congraturation = nil,
    stc_tubalaItemSlot = nil,
    txt_itemName = nil,
    stc_attackPointArea = nil,
    txt_apTitle = nil,
    txt_hitTitle = nil,
    txt_apValue = nil,
    txt_hitValue = nil,
    stc_defencePointArea = nil,
    txt_dpTitle = nil,
    txt_dodTitle = nil,
    txt_RedTitle = nil,
    txt_dpValue = nil,
    txt_dodValue = nil,
    txt_redValue = nil,
    btn_tubalaExchange = nil,
    btn_showTriedStack = nil,
    btn_groupEnchant = nil,
    btn_beginnerGuide = nil
  },
  _ui_extraction = {
    stc_extractionBg = nil,
    stc_extractionAreaBg = nil,
    stc_subTabBg = nil,
    btn_subRadio = {
      [1] = nil,
      [2] = nil
    },
    stc_selectBar = nil,
    stc_line = nil,
    stc_imageArea = nil,
    stc_imageDarkPredation = nil,
    stc_itemSlot = nil,
    txt_stackRate = nil,
    stc_imageSecretBook = nil,
    stc_bookSlot = nil,
    stc_scrollSlot = nil,
    stc_infoArea = nil,
    txt_subTitle = nil,
    txt_valks = nil,
    txt_valksValue = nil,
    txt_plus = nil,
    txt_plusValue = nil,
    stc_verticalLine = nil,
    txt_currentStack = nil,
    stc_arrowIcon = nil,
    txt_resultStack = nil,
    stc_bottomArea = nil,
    txt_extractionDesc = nil,
    chk_skipAni = nil
  },
  _ui_pc = {
    btn_enchantGo = nil,
    btn_extractionGo = nil,
    btn_question = nil,
    btn_close = nil,
    btn_groupEnchantGo = nil,
    chk_inventoryOpen = nil,
    btn_groupEnchantReady = nil
  },
  _ui_console = {
    stc_mainTabLT = nil,
    stc_mainTabRT = nil,
    stc_enchantGoY = nil,
    stc_extractionSubTabLT = nil,
    stc_extractionSubTabRT = nil,
    stc_exractionGoY = nil,
    stc_keyguideBg = nil,
    stc_cancle = nil,
    stc_detail = nil,
    stc_rstick = nil,
    stc_select = nil
  },
  _blablaDesc = {
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_1"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_2"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_3"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_4"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_5"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_6"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_7"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_8"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_9"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_10"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_11"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_12"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_13"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_14"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_15"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_16"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_17"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_18"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_19"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_20"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_21"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_22"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_23"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_24"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_25"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_26"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_27"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_28"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_29"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_30"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_31"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_32"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_33"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_34"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_35"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_36"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_37"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_38"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_39"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_40"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_41"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_42"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_43"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_44"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_45"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_46"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_47"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_48"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_49"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_50"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_51"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_52"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_53"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_54"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_55"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_56"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_57"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_58"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_59"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_60"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_61"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_62"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_63"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_64"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_65"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_66"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_67"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_68"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_69"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_70"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_71"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_72"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_73"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_74"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_75"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_76"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_77"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_78"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_79"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_80"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_81"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_82"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_83"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_84"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_85"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_86"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_87"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_88"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_89"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_90"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_91"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_92"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_93"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_94"),
    PAGetString(Defines.StringSheet_GAME, "LUA_ENCHANT_BLABLADESC_95")
  },
  _slotConfig = {
    createIcon = true,
    createBorder = true,
    createCount = false,
    createEnchant = true,
    createCash = true,
    createOriginalForDuel = true
  },
  _slotConfig_count = {
    createIcon = true,
    createBorder = true,
    createCount = true,
    createEnchant = true,
    createCash = true
  },
  _slotConfig_caphras = {
    createIcon = true,
    createBorder = false,
    createCount = false,
    createEnchant = true,
    createCash = true
  },
  _strForEnchantInfo = {
    _forcedChecked = "",
    _cronChecked = "",
    _defenceFailChecked = "",
    _notChecked = ""
  },
  _enchantBtnType = {
    normal = 1,
    perfect = 2,
    force = 3,
    cron = 4
  },
  _enum_EnchantType = {
    _safe = 0,
    _unsafe = 1,
    _broken = 2,
    _gradedown = 3,
    _downAndBroken = 4
  },
  _enum_EnchantResult = {
    _success = 0,
    _broken = 1,
    _gradedown = 2,
    _fail = 3,
    _failAndPrevent = 4,
    _error = 5
  },
  _MAIN_TAB = {
    ENCHANT = 1,
    CARPHRAS = 2,
    EXTRACTION = 3
  },
  _SUB_TAB = {DARK = 1, BOOK = 2},
  _currentMainTab = 0,
  _currentSubTab = 0,
  _isWaitingServer = false,
  _isSetNewPerfectItemMaterial = false,
  _isLastEnchant = false,
  _slotEquip = {},
  _slotMateiralInfo = {},
  _materialNeedCount = 0,
  _currentEnchantRate = 0,
  _slotResult_Caphras = {},
  _slotEquip_Caphras = {},
  _slotMaterial_Caphras = {},
  _slotDarkItem = {},
  _slotBookItem = {},
  _slotValksItem = {},
  _slotTubala = {},
  _tubalaItemKey = nil,
  _naruItemWhereType = nil,
  _naruItemSlotNo = nil,
  _caphrasStatsMaxCount = 8,
  _isPossiblePromotion = false,
  _isPossibleMaterial = false,
  _grantItemWhereType = nil,
  _grantItemSlotNo = nil,
  _materialItemSlotNo = nil,
  _materialItemWhereType = nil,
  _isMaterialSlotMonotone = false,
  _defaultSlotCount = 3,
  _isShow_forceEnchant = false,
  _isShow_perfectEnchant = false,
  _isShow_cronEnchant = false,
  _isShow_defenceFailEnchant = false,
  _isAniSkip = false,
  _isAnimating = false,
  _animationTimeStamp = 0,
  _effectTime = 7.5,
  _originEffectTime = 7.5,
  _startTime = 6,
  _isStart = false,
  _isClickCancle = false,
  _nakAniTimeStamp = 0,
  _nakElapsedTime = 2.3,
  _isNakAnimating = false,
  _originNakSpanY = 120,
  _originPanelSizeY = 0,
  _originEnchantBGSizeY = 0,
  _originEnchantInfoBGSizeY = 0,
  _originEnchantButtonAreaPosY = 0,
  _originExtractionBottomBGSizeY = 0,
  _originExtractionButtonAreaPosY = 0,
  _originEnchnatNoticeBgSizeY = 0,
  _originEnchnatNoticeBgPosY = 0,
  _originTubalaExchangeBtnSizeX = 0,
  _darkPredationRate = 100,
  _darkPredationValue = 0,
  _failCountExtractEnable = false,
  _enchantInfo = nil,
  _isEnchantAniSkip = false,
  _isCaphrasAniSkip = false,
  _isDarkAniSkip = false,
  _isBookAniSkip = false,
  _failCountToItemKeyEx = nil,
  _isGroupEnchantPartyMember = false,
  _isLeaderGroupEnchantMode = false,
  _isEndGroupEnchant = false,
  _isGroupEnchantReady = false,
  _isAdventureEnchant = false,
  _savedDarkItemSlotNo = nil,
  _savedDarkItemItemWrapper = nil,
  _savedDarkItemInventoryType = nil,
  _savedCaphrasInvenCount = 0,
  _savedCaphrasCountSetSlot = 0,
  _const = {
    bottomBgOriSizeY = 170,
    bottomBgMidSizeY = 130,
    bottomBgCaphrasSizeY = 130,
    bottomBgMaxSizeY = 130,
    kindDescSpanTopY = 20,
    kindDescSpnaMidY = 180
  },
  _isConsole = _ContentsGroup_UsePadSnapping,
  _isContents_Enable = ToClient_IsContentsGroupOpen("74"),
  _isContents_CronEnchantOpen = ToClient_IsContentsGroupOpen("234"),
  _initialize = false,
  _isAbleCaphras = false,
  _isAbleEnchant = false,
  _originAudio = {idx = 5, idxB = 9},
  _enchantEffect = {
    [1] = {
      effectName = "fUI_SpiritEnchant_High_2s_01A",
      effectTime = 6,
      audioIndex = 5,
      audioIndexB = 21
    },
    [2] = {
      effectName = "fUI_SpiritEnchant_High_01A",
      effectTime = 7,
      audioIndex = 5,
      audioIndexB = 24
    },
    [3] = {
      effectName = "fUI_SpiritEnchant_High_4s_01A",
      effectTime = 8,
      audioIndex = 5,
      audioIndexB = 25
    },
    [4] = {
      effectName = "fUI_SpiritEnchant_High_5s_01A",
      effectTime = 9,
      audioIndex = 5,
      audioIndexB = 26
    }
  },
  _randomEffectNum = 0,
  _isEnchantPerfect = false,
  _prevMaterialSlotNo = nil,
  _currMaterialSlotNo = nil,
  _audio = {
    _enchatNomal_idxB = 20,
    _enchatLast_idxB = 21,
    _caphras_idxB = 30,
    _dark_idxB = 40,
    _book_idxB = 60
  },
  _groupEnchant = {
    _resultType,
    _mainWhereType,
    _mainSlotNo,
    _subWhereType,
    _subSlotNo
  },
  _tooltipSpanX = 0,
  _lastFamilyStackSlotScroll = 0,
  _familyStackDeltaTime = 0,
  _isMaxStackEnchant = false,
  _enchantFailureRv = 0
}
runLua("UI_Data/Script/Window/Enchant/Panel_Window_SpiritEnchant_All_1.lua")
runLua("UI_Data/Script/Window/Enchant/Panel_Window_SpiritEnchant_All_2.lua")
runLua("UI_Data/Script/Window/Enchant/Panel_Window_SpiritEnchant_All_3.lua")
runLua("UI_Data/Script/Window/Enchant/Panel_Window_SpiritEnchant_All_4.lua")
runLua("UI_Data/Script/Window/Enchant/Panel_Window_SpiritEnchant_All_5.lua")
runLua("UI_Data/Script/Window/Enchant/Panel_Window_SpiritEnchant_All_6.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_SpiritEnchant_All_Init")
function FromClient_SpiritEnchant_All_Init()
  PaGlobal_SpiritEnchant_All:initialize()
end
