PaGlobal_ArtifactsExchange = {
  _ui = {
    stc_TitleBarArea = nil,
    btn_Close = nil,
    stc_RadioButtonBG = nil,
    rdo_Exchange = nil,
    rdo_Purify = nil,
    stc_SelectBar = nil,
    stc_ExchangeBG = nil,
    stc_ExchangeEffect = nil,
    stc_ExchangeRewardSlot = nil,
    txt_ExchangeDesc = nil,
    txt_ExchangeMultiline = nil,
    txt_ExchangeFinish = nil,
    frame = nil,
    frame_Content = nil,
    frame_VerticalScroll = nil,
    stc_ExchangeSlot = nil,
    btn_PutInAll = nil,
    chk_ExchangeSkipAni = nil,
    btn_Exchange = nil,
    stc_PurifyBG = nil,
    stc_PurifyEffect = nil,
    stc_PurifyBaseBG = nil,
    stc_PurifyFireBG = nil,
    stc_PurifyEarthBG = nil,
    stc_PurifyWindBG = nil,
    stc_PurifyGrassBG = nil,
    stc_PurifyRewardSlot = nil,
    txt_PurifyDesc = nil,
    txt_PurifyMultiline = nil,
    txt_PurifyFinish = nil,
    stc_Material = nil,
    stc_PurifySlotBG = nil,
    stc_PurifySlot = nil,
    stc_SilverBG = nil,
    stc_SilverValue = nil,
    stc_MoneyArea = nil,
    txt_MoneyValue = nil,
    chk_PurifySkipAni = nil,
    btn_Purify = nil,
    stc_LBUI = nil,
    stc_RBUI = nil,
    stc_BottomConsole = nil,
    btn_KeyGuideDetail = nil,
    btn_KeyGuideSelect = nil,
    btn_KeyGuideCancel = nil,
    btn_KeyGuidePurify = nil,
    btn_KeyGuideExchange = nil,
    btn_KeyGuidePushAll = nil
  },
  _exchangeSlots = {},
  _exchangeAddedSlotNo = {},
  _exchangeRewardSlot = nil,
  _purifySlot = nil,
  _purifyItemKeyList = {},
  _purifyRewardSlot = nil,
  _needPurifyPrice = toInt64(0, 0),
  _exchangeSlotMaxCount = 30,
  _purifyPrice = 0,
  _scrollIndex = 0,
  _isShowTooltip = false,
  _aniStart = false,
  _isExchange = true,
  _const_Exchange_AniTime = 2,
  _delta_Exchange_AniTime = 0,
  _const_Purify_AniTime = 2,
  _delta_Purify_AniTime = 0,
  _panelSizeY = nil,
  _isConsole = _ContentsGroup_UsePadSnapping,
  _initialize = false
}
runLua("UI_Data/Script/Window/Artifacts/Panel_Window_Artifacts_Exchange_All_1.lua")
runLua("UI_Data/Script/Window/Artifacts/Panel_Window_Artifacts_Exchange_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_Artifacts_Exchange_All_Init")
function FromClient_Artifacts_Exchange_All_Init()
  PaGlobal_ArtifactsExchange:initialize()
end
