PaGlobal_ExchangeCoin_All = {
  _ui = {
    stc_static1 = nil,
    stc_sizeFix = nil,
    stc_listArea = nil,
    stc_tabArea = nil,
    rdo_tabMenu = nil,
    rdo_tabSeason = nil,
    rdo_tabEvent = nil,
    rdo_tabContents = nil,
    rdo_tabBookmark = nil,
    rdo_tabBossReward = nil,
    stc_keyGuide_LB = nil,
    stc_keyGuide_RB = nil,
    stc_tabSelect = nil,
    stc_tabName = nil,
    list2_moneyList = nil,
    list2_content = nil,
    scroll_vertical = nil,
    scroll_horizontal = nil,
    edit_searchText = nil,
    btn_search = nil,
    stc_LT_X = nil,
    btn_reset = nil,
    stc_infoArea = nil,
    stc_itemBG = nil,
    stc_item = nil,
    txt_itemName = nil,
    txt_hasCount = nil,
    txt_itemDesc = nil,
    txt_exchangeTitle = nil,
    stc_lineDeco_t = nil,
    stc_lineDeco_b = nil,
    frame_exchangeList = nil,
    frame_1_content = nil,
    stc_familyExchange = nil,
    stc_weeklyExchange = nil,
    stc_dailyExchange = nil,
    stc_alwaysExchange = nil,
    stc_template = nil,
    frame_1_verticalScroll = nil,
    frame_1_horizontalScroll = nil,
    stc_KeyGuide_Console = nil,
    stc_consoleB = nil,
    stc_consoleA = nil,
    stc_consoleX = nil,
    stc_consoleY = nil,
    btn_close = nil
  },
  _config = {
    COIN_GRID_COLUMN = 3,
    COIN_GRID_ROW = 5,
    REWARD_GRID_COLUMN = 2
  },
  _slotConfig = {
    createIcon = true,
    createBorder = true,
    createCount = true,
    createEnchant = true
  },
  _selectedSlotConfig = {createIcon = true, createBorder = true},
  _exchangeTypeEnum = {
    ALWAYS = 0,
    DAY = 1,
    WEEK = 2,
    FAMILY = 3,
    COUNT = 4
  },
  _coinList = {},
  _coinListToIndex = 0,
  _selectedCoinItemKey = nil,
  _selectedCoinSlot = nil,
  _selectedCategoryIndex = 0,
  _eCatergoryTabOrder = {
    ALL = 0,
    SEASON = 1,
    EVENT = 2,
    CONTENTS = 3,
    BOSSREWARD = 4,
    BOOKMARK = 5,
    COUNT = 6
  },
  _familyRewardControl = nil,
  _weeklyRewardControl = nil,
  _dailyRewardControl = nil,
  _alwaysRewardControl = nil,
  _totalSizeYList = nil,
  _filterText = "",
  _msgBoxCoinItemKey = nil,
  _msgBoxExchangeNo = nil,
  _msgBoxExchangeCount = nil,
  _isConsole = false,
  _rewardControlList = nil,
  _coinControlList = nil,
  _firstRewardControl = nil,
  _rewardCtrlRow = 0,
  _scale = 1,
  _initialize = false
}
runLua("UI_Data/Script/Window/Exchange/Panel_ExchangeCoin_All_1.lua")
runLua("UI_Data/Script/Window/Exchange/Panel_ExchangeCoin_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_ExchangeCoin_Init")
function FromClient_ExchangeCoin_Init()
  PaGlobal_ExchangeCoin_All:initialize()
end
