PaGlobal_MorningLand_Boss_All = {
  _ui = {
    stc_titleArea = nil,
    btn_closePC = nil,
    stc_tabArea = nil,
    rdo_MorningLandPart1 = nil,
    rdo_MorningLandPart2 = nil,
    stc_selectBar = nil,
    stc_mainArea = nil,
    stc_mainContentsLock = nil,
    stc_mainContents = nil,
    txt_conqeustCount = nil,
    btn_conquestHistory = nil,
    txt_bossWeeknessTitle = nil,
    stc_bossWeeknessBg = nil,
    txt_bossWeekness = nil,
    stc_rewardBox = nil,
    txt_bossName = nil,
    txt_bossDesc = nil,
    stc_difficulty = nil,
    txt_difficulty = nil,
    stc_clearChar = nil,
    txt_clearChar = nil,
    stc_clearTimeRecord = nil,
    txt_clearTimeRecord = nil,
    stc_clearTime = nil,
    txt_clearTime = nil,
    btn_conquestStart = nil,
    btn_moveToWayPoint = nil,
    btn_conquestEnter = nil,
    txt_enter = nil,
    btn_conquestEnterParty = nil,
    txt_enterParty = nil,
    btn_attributeManage = nil,
    btn_rankingView = nil,
    btn_MyReward = nil,
    stc_getAble = nil,
    btn_ranking = nil,
    btn_myReward = nil,
    stc_difficultyMorning2 = nil,
    rdo_difficultyMorning2_Easy = nil,
    rdo_difficultyMorning2_Hard = nil,
    btn_rankingViewMorning2 = nil,
    stc_txtBubble = nil,
    stc_princessImage = nil,
    txt_bubble = nil,
    stc_statManageArea = nil,
    stc_statView = nil,
    btn_attributeViewReset = nil,
    stc_statContents = nil,
    btn_attribute0 = nil,
    btn_attribute1 = nil,
    btn_attribute2 = nil,
    txt_effectDesc = nil,
    stc_attributePointBox = nil,
    txt_attributePoint = nil,
    stc_attributeEnergyBox = nil,
    btn_attributeReset = nil,
    txt_myStatTitle = nil,
    stc_myStatPointBox = nil,
    txt_myStatPoint = nil,
    btn_myStatReset = nil,
    stc_statAttackBox = nil,
    txt_statAttackTitle = nil,
    txt_statAttack = nil,
    btn_attackUp = nil,
    stc_statDeffenceBox = nil,
    txt_statDefTitle = nil,
    txt_statDeffence = nil,
    btn_deffenceUp = nil,
    btn_statApply = nil,
    btn_attributeClose = nil,
    btn_attributeSet = nil,
    list2_bossList = nil,
    list2_bossContent = nil,
    scroll_vertical = nil,
    scroll_horizontal = nil,
    list2_bossListMorning2 = nil,
    stc_noticeArea = nil,
    stc_keyGuide = nil,
    stc_key_LT_Y = nil,
    stc_key_LT_X = nil,
    stc_key_LT_A = nil,
    stc_key_Y = nil,
    stc_key_X = nil,
    stc_key_A = nil,
    stc_key_B = nil,
    stc_key_LB = nil,
    stc_key_RB = nil
  },
  _statType = {
    Elemental = 0,
    Offence = 1,
    Deffence = 2
  },
  _statConfirmType = {
    Elemental = 0,
    Stat = 1,
    Both = 2
  },
  _bossList = {},
  _bossListMorning2 = {},
  _attributeEnergyList = {},
  _difficultyList = {},
  _rewardBtnList = {},
  _listShowRewardSlots = {},
  _statViewList = {},
  _attributeList = {},
  _attributeEnergyViewList = {},
  _sideBtnList = {},
  _sideBtnShowList = {},
  _sideBtnShowListMorning2 = {},
  _attributeEnergyUV = {
    [__eElementalStat_Sun] = "Combine_Etc_MorningLand_Boss_01_Icon_Bead_Sun",
    [__eElementalStat_Moon] = "Combine_Etc_MorningLand_Boss_01_Icon_Bead_Moon",
    [__eElementalStat_Land] = "Combine_Etc_MorningLand_Boss_01_Icon_Bead_Land"
  },
  _attributeDesc = {
    [__eElementalStat_Sun] = "LUA_MORNING_ATTRBOSS_SUN",
    [__eElementalStat_Moon] = "LUA_MORNING_ATTRBOSS_MOON",
    [__eElementalStat_Land] = "LUA_MORNING_ATTRBOSS_SOIL"
  },
  _attributeDetail = {
    [__eElementalStat_Sun] = "LUA_MORNING_ATTRBOSS_SUN_DESC",
    [__eElementalStat_Moon] = "LUA_MORNING_ATTRBOSS_MOON_DESC",
    [__eElementalStat_Land] = "LUA_MORNING_ATTRBOSS_SOIL_DESC"
  },
  _bossWeeknessUV = {
    [__eElementalStat_Sun] = "Combine_Etc_MorningLand_Boss_01_Icon_Quality_Sun",
    [__eElementalStat_Moon] = "Combine_Etc_MorningLand_Boss_01_Icon_Quality_Moon",
    [__eElementalStat_Land] = "Combine_Etc_MorningLand_Boss_01_Icon_Quality_Land"
  },
  _frmBossWeeknessUV = {
    [__eElementalStat_Sun] = "Combine_Etc_MorningLand_Boss_01_Icon_Quality_Sun_Big",
    [__eElementalStat_Moon] = "Combine_Etc_MorningLand_Boss_01_Icon_Quality_Moon_Big",
    [__eElementalStat_Land] = "Combine_Etc_MorningLand_Boss_01_Icon_Quality_Land_Big"
  },
  _bossListUV = {
    [0] = "Combine_Etc_MorningLand_Boss_01_List_Profile_06",
    [1] = "Combine_Etc_MorningLand_Boss_01_List_Profile_07",
    [2] = "Combine_Etc_MorningLand_Boss_01_List_Profile_09",
    [3] = "Combine_Etc_MorningLand_Boss_01_List_Profile_03",
    [4] = "Combine_Etc_MorningLand_Boss_01_List_Profile_04",
    [5] = "Combine_Etc_MorningLand_Boss_01_List_Profile_08",
    [6] = "Combine_Etc_MorningLand_Boss_01_List_Profile_01",
    [7] = "Combine_Etc_MorningLand_Boss_01_List_Profile_02",
    [8] = "Combine_Etc_MorningLand_Boss_01_List_Profile_05",
    [9] = "Combine_Etc_MorningLand_Boss_01_List_Profile_11",
    [10] = "Combine_Etc_MorningLandPt2_Boss_01_List_Profile_05",
    [11] = "Combine_Etc_MorningLandPt2_Boss_01_List_Profile_07",
    [12] = "Combine_Etc_MorningLandPt2_Boss_01_List_Profile_01",
    [13] = "Combine_Etc_MorningLandPt2_Boss_01_List_Profile_03",
    [14] = "Combine_Etc_MorningLandPt2_Boss_01_List_Profile_04",
    [15] = "Combine_Etc_MorningLandPt2_Boss_01_List_Profile_10",
    [16] = "Combine_Etc_MorningLandPt2_Boss_01_List_Profile_02",
    [17] = "Combine_Etc_MorningLandPt2_Boss_01_List_Profile_06",
    [18] = "Combine_Etc_MorningLandPt2_Boss_01_List_Profile_08",
    [19] = "Combine_Etc_MorningLandPt2_Boss_01_List_Profile_09",
    [20] = "Combine_Etc_MorningLandPt2_Boss_01_List_Profile_11",
    [21] = "Combine_Etc_MorningLandPt2_Boss_01_List_Profile_12"
  },
  _bossMainUVStr = {
    [0] = "Combine_Etc_MorningLand_BossProfile_04",
    [1] = "Combine_Etc_MorningLand_BossProfile_07",
    [2] = "Combine_Etc_MorningLand_BossProfile_09",
    [3] = "Combine_Etc_MorningLand_BossProfile_03",
    [4] = "Combine_Etc_MorningLand_BossProfile_05",
    [5] = "Combine_Etc_MorningLand_BossProfile_08",
    [6] = "Combine_Etc_MorningLand_BossProfile_01",
    [7] = "Combine_Etc_MorningLand_BossProfile_02",
    [8] = "Combine_Etc_MorningLand_BossProfile_06",
    [9] = "Combine_Etc_MorningLand_BossProfile_11",
    [10] = "Combine_Etc_MorningLandPt2_GuildBossProfile_05",
    [11] = "Combine_Etc_MorningLandPt2_GuildBossProfile_07",
    [12] = "Combine_Etc_MorningLandPt2_GuildBossProfile_01",
    [13] = "Combine_Etc_MorningLandPt2_GuildBossProfile_03",
    [14] = "Combine_Etc_MorningLandPt2_GuildBossProfile_04",
    [15] = "Combine_Etc_MorningLandPt2_GuildBossProfile_10",
    [16] = "Combine_Etc_MorningLandPt2_GuildBossProfile_02",
    [17] = "Combine_Etc_MorningLandPt2_GuildBossProfile_06",
    [18] = "Combine_Etc_MorningLandPt2_GuildBossProfile_08",
    [19] = "Combine_Etc_MorningLandPt2_GuildBossProfile_09",
    [20] = "Combine_Etc_MorningLandPt2_GuildBossProfile_11",
    [21] = "Combine_Etc_MorningLandPt2_GuildBossProfile_12"
  },
  _bossListUVMorning2 = {},
  _bossMainUVStrMorning2 = {},
  _effectChar = {
    [0] = "A",
    [1] = "B",
    [2] = "C"
  },
  _energyButtonEffectChar = {
    [0] = "B",
    [1] = "C",
    [2] = "D"
  },
  _mainBossEffectChar = {
    [1] = "A",
    [2] = "A",
    [3] = "A",
    [4] = "A",
    [5] = "A",
    [6] = "B",
    [7] = "B",
    [8] = "B",
    [9] = "C",
    [10] = "C"
  },
  _zeroUV = "Combine_Etc_MorningLand_Boss_01_Icon_Bead_Zero",
  _levelUV = {
    levelNormal = 0,
    levelNormalOver = 1,
    levelClear = 2,
    levelClearOver = 3
  },
  _descType = {
    history = 0,
    week = 1,
    statManage = 2,
    rank = 3,
    reward = 4,
    sun = 5,
    moon = 6,
    land = 7,
    light = 8,
    addPoint = 9,
    sunDetail = 10,
    moonDetail = 11,
    landDetail = 12,
    lightDetail = 13,
    guildRank = 14
  },
  _storedElementalStat = {
    [__eElementalStat_Sun] = {
      [0] = 0,
      [1] = 0,
      [2] = 0
    },
    [__eElementalStat_Moon] = {
      [0] = 0,
      [1] = 0,
      [2] = 0
    },
    [__eElementalStat_Land] = {
      [0] = 0,
      [1] = 0,
      [2] = 0
    }
  },
  _targetControlList = {},
  _initialize = false,
  _selectedmorningBossKey = nil,
  _isConsole = false,
  _selectedType = __eElementalStat_Sun,
  _selectedBoss = 0,
  _selectedBossGroupIndex = 0,
  _lastSelectedBossGroupMorning1 = 0,
  _lastSelectedBossGroupMorning2 = 0,
  _elementStatMax = 10,
  _storedAddPoint = 0,
  _clearStatType = 0,
  _isAddEffect = false,
  _isUnlockOne = false,
  _isAbleElementalReset = false,
  _isAbleStatReset = false,
  _isWorldMapOpen = false,
  _clearTimePosY = 0,
  _MORNINGLAND_PART1_BOSSCOUNT = 10,
  _MORNINGLAND_PART2_BOSSCOUNT = 20,
  _tooltipInfo_Pad = {_index = nil, _monsterKeyRaw = nil},
  _selectedBossGroup = 0,
  _selectedLevel = 0,
  _selectedMaxClearLevel = 0,
  _morningLandPart = {eMorningLandPart1 = 1, eMorningLandPart2 = 2}
}
runLua("UI_Data/Script/Window/MorningLand/Panel_Window_MorningLand_Boss_All_1.lua")
runLua("UI_Data/Script/Window/MorningLand/Panel_Window_MorningLand_Boss_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_MorningLand_Boss_Init")
function FromClient_MorningLand_Boss_Init()
  PaGlobal_MorningLand_Boss_All:initialize()
end
