PaGlobal_QuickTimeEvent_Manager = {
  _initialize = false,
  _keyEventList = {},
  _timeAccum = 0,
  _currentUIType = 0,
  UITYPE = {
    TYPE_CIRCLE = 0,
    TYPE_LINE = 1,
    TYPE_CIRCLECOUNT = 2,
    TYPE_NONE = 3
  },
  _panelList = {},
  _luaList = {},
  KEYEVENTSTATE = {
    NONE = 0,
    PROCESSING = 1,
    SUCCESS = 3,
    FAIL = 4,
    COUNT = 5
  },
  _currentState = 0,
  _keyString = {
    [CppEnums.VirtualKeyCode.KeyCode_ESCAPE] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_Esc"),
    [CppEnums.VirtualKeyCode.KeyCode_F1] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F1"),
    [CppEnums.VirtualKeyCode.KeyCode_F2] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F2"),
    [CppEnums.VirtualKeyCode.KeyCode_F3] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F3"),
    [CppEnums.VirtualKeyCode.KeyCode_F4] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F4"),
    [CppEnums.VirtualKeyCode.KeyCode_F5] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F5"),
    [CppEnums.VirtualKeyCode.KeyCode_F6] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F6"),
    [CppEnums.VirtualKeyCode.KeyCode_F7] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F7"),
    [CppEnums.VirtualKeyCode.KeyCode_F8] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F8"),
    [CppEnums.VirtualKeyCode.KeyCode_F9] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F9"),
    [CppEnums.VirtualKeyCode.KeyCode_F10] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F10"),
    [CppEnums.VirtualKeyCode.KeyCode_F11] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F11"),
    [CppEnums.VirtualKeyCode.KeyCode_F12] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F12"),
    [CppEnums.VirtualKeyCode.KeyCode_1] = "1",
    [CppEnums.VirtualKeyCode.KeyCode_2] = "2",
    [CppEnums.VirtualKeyCode.KeyCode_3] = "3",
    [CppEnums.VirtualKeyCode.KeyCode_4] = "4",
    [CppEnums.VirtualKeyCode.KeyCode_5] = "5",
    [CppEnums.VirtualKeyCode.KeyCode_6] = "6",
    [CppEnums.VirtualKeyCode.KeyCode_7] = "7",
    [CppEnums.VirtualKeyCode.KeyCode_8] = "8",
    [CppEnums.VirtualKeyCode.KeyCode_9] = "9",
    [CppEnums.VirtualKeyCode.KeyCode_0] = "0",
    [CppEnums.VirtualKeyCode.KeyCode_NUMPAD1] = "1",
    [CppEnums.VirtualKeyCode.KeyCode_NUMPAD2] = "2",
    [CppEnums.VirtualKeyCode.KeyCode_NUMPAD3] = "3",
    [CppEnums.VirtualKeyCode.KeyCode_NUMPAD4] = "4",
    [CppEnums.VirtualKeyCode.KeyCode_NUMPAD5] = "5",
    [CppEnums.VirtualKeyCode.KeyCode_NUMPAD6] = "6",
    [CppEnums.VirtualKeyCode.KeyCode_NUMPAD7] = "7",
    [CppEnums.VirtualKeyCode.KeyCode_NUMPAD8] = "8",
    [CppEnums.VirtualKeyCode.KeyCode_NUMPAD9] = "9",
    [CppEnums.VirtualKeyCode.KeyCode_NUMPAD0] = "0",
    [CppEnums.VirtualKeyCode.KeyCode_TAB] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_Tab"),
    [CppEnums.VirtualKeyCode.KeyCode_Q] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_Q"),
    [CppEnums.VirtualKeyCode.KeyCode_W] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_W"),
    [CppEnums.VirtualKeyCode.KeyCode_E] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_E"),
    [CppEnums.VirtualKeyCode.KeyCode_R] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_R"),
    [CppEnums.VirtualKeyCode.KeyCode_T] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_T"),
    [CppEnums.VirtualKeyCode.KeyCode_Y] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_Y"),
    [CppEnums.VirtualKeyCode.KeyCode_U] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_U"),
    [CppEnums.VirtualKeyCode.KeyCode_I] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_I"),
    [CppEnums.VirtualKeyCode.KeyCode_O] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_O"),
    [CppEnums.VirtualKeyCode.KeyCode_P] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_P"),
    [CppEnums.VirtualKeyCode.KeyCode_A] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_A"),
    [CppEnums.VirtualKeyCode.KeyCode_S] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_S"),
    [CppEnums.VirtualKeyCode.KeyCode_D] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_D"),
    [CppEnums.VirtualKeyCode.KeyCode_F] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_F"),
    [CppEnums.VirtualKeyCode.KeyCode_G] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_G"),
    [CppEnums.VirtualKeyCode.KeyCode_H] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_H"),
    [CppEnums.VirtualKeyCode.KeyCode_J] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_J"),
    [CppEnums.VirtualKeyCode.KeyCode_K] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_K"),
    [CppEnums.VirtualKeyCode.KeyCode_L] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_L"),
    [CppEnums.VirtualKeyCode.KeyCode_RETURN] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_Enter"),
    [CppEnums.VirtualKeyCode.KeyCode_SHIFT] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_Shift"),
    [CppEnums.VirtualKeyCode.KeyCode_Z] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_Z"),
    [CppEnums.VirtualKeyCode.KeyCode_X] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_X"),
    [CppEnums.VirtualKeyCode.KeyCode_C] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_C"),
    [CppEnums.VirtualKeyCode.KeyCode_V] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_V"),
    [CppEnums.VirtualKeyCode.KeyCode_B] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_B"),
    [CppEnums.VirtualKeyCode.KeyCode_N] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_N"),
    [CppEnums.VirtualKeyCode.KeyCode_M] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_M"),
    [CppEnums.VirtualKeyCode.KeyCode_SHIFT] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_Shift"),
    [CppEnums.VirtualKeyCode.KeyCode_SPACE] = PAGetString(Defines.StringSheet_GAME, "InputCustomizer_Space")
  },
  _initialize = false
}
runLua("UI_Data/Script/Window/Cutscene/Panel_Window_QuickTimeEvent_Manager_1.lua")
runLua("UI_Data/Script/Window/Cutscene/Panel_Window_QuickTimeEvent_Manager_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_QuickTimeEvent_Manager_Init")
PaGlobal_QuickTimeEvent_Manager:initialize()
function FromClient_QuickTimeEvent_Manager_Init()
  PaGlobal_QuickTimeEvent_Manager:initialize()
end
