PaGlobal_ChatOption_All = {
  _ui = {
    stc_mainBg = nil,
    btn_close = nil,
    btn_question = nil,
    txt_title = nil,
    stc_transparentBg = nil,
    btn_reset_color = nil,
    stc_chatViewBg = nil,
    btn_selectAll = nil,
    btn_deSelectAll = nil,
    stc_selectTemplate = nil,
    stc_selectBgTemplate = nil,
    chk_selectCheckTemplate = nil,
    btn_selectColorTemplate = nil,
    stc_systemTitleBg = nil,
    stc_systemBtn = nil,
    stc_systemTitleOn = nil,
    chk_systemSelect = nil,
    rdo_systemColor = nil,
    chk_systemTemplate = nil,
    stc_emogiTitleBg = nil,
    stc_emogiTitleIcon = nil,
    stc_textSizeBg = nil,
    stc_scrollAniBg = nil,
    stc_emogiBg = nil,
    stc_optionBg = nil,
    stc_banBgs = nil,
    btn_banList = nil,
    stc_arabBg = nil,
    btn_groupChat = nil,
    btn_confirm = nil,
    btn_cancle = nil
  },
  _ban_ui = {
    stc_banList = nil,
    stc_banTitle = nil,
    btn_banClose = nil,
    btn_banQuestion = nil,
    list2_ban = nil,
    btn_banDelete = nil,
    btn_banDeleteAll = nil
  },
  _fontSizeType = {
    verySmall = 10,
    small = 12,
    normal = 14,
    big = 16,
    veryBig = 18
  },
  _chatOptionData = {
    makeChatPanelCount = 5,
    chatFilterCount = 14,
    chatSystemFilterCount = 8,
    useSystemFilterCount = 0
  },
  _eChatButtonType = {
    eChatNotice = 0,
    eChatWorldWithItem = 1,
    eChatWorld = 2,
    eChatGuild = 3,
    eChatParty = 5,
    eChatBattle = 4,
    eChatPublic = 6,
    eChatPrivate = 7,
    eChatRolePlay = 8,
    eChatArsha = 9,
    eChatTeam = 10,
    eChatAlliance = 11,
    eChatChannelChatting = 12,
    eChatGuildManager = 13
  },
  _eChatSystemButtonType = {
    eChatSystem = 0,
    eChatSystemUndefine = 1,
    eChatSystemPrivateItem = 2,
    eChatSystemPartyItem = 3,
    eChatSystemMarket = 4,
    eChatSystemWorker = 5,
    eChatSystemHarvest = 6,
    eChatSystemEnchant = 7
  },
  _panelIndex = nil,
  _drawPanelIndex = nil,
  _isCombinedMainPanel = false,
  _isPrevValueSaving = false,
  _prevTransparency = -1,
  _prevIsCheckDivision = true,
  _prevIsCheckChatTime = {},
  _preChattingAnimation = true,
  _preEmoticonAutoPlay = true,
  _prevFontSizeType = CppEnums.ChatFontSizeType.eChatFontSizeType_Normal,
  _preUseHarfBuzz = false,
  _preNameType = nil,
  _isUseEmoticonAutoPlay = nil,
  _isChangeFontSize = true,
  _selectBlockIndex = -1,
  _btnFilter = Array.new(),
  _btnSystemFilter = Array.new(),
  _chatPanelSet = Array.new(),
  _channelFilter = {},
  _channelSystemFilter = {},
  _isLocalWarOpen = ToClient_IsContentsGroupOpen("43"),
  _isArshaOpen = _ContentsGroup_Arsha,
  _isSavageDefenceOpen = ToClient_IsContentsGroupOpen("249"),
  _isRoleplayTypeOpen = isGameTypeEnglish() or isGameServiceTypeDev(),
  _isGuildAlianceOpen = _ContentsGroup_guildAlliance,
  _isChannelChatOpen = _ContentsGroup_ChannelChat,
  _isItemMarketKor2Open = _ContentsGroup_ItemMarketKor2,
  _isEmotionAutoPlayOpen = _ContentsGroup_Emoticon,
  _isConsole = false,
  _initialize = false
}
runLua("UI_Data/Script/Widget/Chatting/Panel_Window_ChatOption_All_1.lua")
runLua("UI_Data/Script/Widget/Chatting/Panel_Window_ChatOption_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_ChatOption_All_Init")
function FromClient_ChatOption_All_Init()
  PaGlobal_ChatOption_All:initialize()
end
