PaGlobal_DeadMessage_All = {
  _ui = {
    stc_centerBG = nil,
    txt_deathTitle = nil,
    txt_resurrectionTime = nil,
    txt_GuildSkillApply = nil,
    stc_lostItemBG = nil,
    stc_lineTop = nil,
    stc_lineBottom = nil,
    list2_lostItem = nil,
    list2_content = nil,
    stc_resurrectionBG = nil,
    btn_largeTemplate = nil,
    btn_smallTemplate = nil,
    _button_Respawn = {},
    btn_noticeIcon = nil,
    btn_selectButton_console = nil,
    btn_useItemCheck = nil,
    btn_useFairyCheck = nil,
    stc_paneltyBG = nil,
    btn_specUpGuideIcon = nil,
    btn_restoreJewel = nil,
    btn_restoreJewelTooltip = nil
  },
  _eButtonType = {
    GuildObServerMode = 1,
    Observer = 2,
    SavageDefence = 3,
    Immediate = 4,
    InSiegeingFortress = 5,
    LocalWar = 6,
    GuildBatle = 7,
    OutsideGate = 8,
    InsideGate = 9,
    ByOtherPlayer = 10,
    Exploration = 11,
    NearTown = 12,
    AdvancedBase = 13,
    GuildSpawn = 14,
    Competition = 15,
    TimeOver = 16,
    ExitBloodAltar = 17,
    Atoraxion = 18,
    SolareObserver = 19,
    AbyssOne = 20,
    AbyssOneBase = 21,
    AbyssOneExit = 22,
    GuildMatch = 23,
    Siege2024RevivePosition0 = 24,
    Siege2024RevivePosition1 = 25,
    Siege2024RevivePosition2 = 26,
    Siege2024RevivePosition3 = 27,
    count = 28
  },
  _eDeadType = {
    Dead_Normal = 0,
    DeadLocate_InBattleGround = 1,
    DeadLocate_InCompetition = 2,
    DeadLocate_InSavageDefence = 3,
    DeadLocate_InGuildBattle = 4,
    DeadLocate_InPVP = 5,
    DeadLocate_InLocarWar = 6,
    DeadLocate_InPrision = 7,
    DeadLocate_InSiegeBeingChannel = 8,
    DeadLocate_InSiegeBeingInCurrentPos = 9,
    DeadLocate_InSiegeBattle = 10,
    DeadLocate_InMajorSiegeBattle = 11,
    DeadLocate_InNoAccessArea = 12,
    DeadLocate_InArena = 13,
    IsPremiumCharacter = 14,
    DeadLocate_InBloodAltar = 15,
    DeadLocate_InAtoraxion = 16,
    DeadLocate_InSolare = 17,
    DeadLocate_InAbyssOne = 18,
    DeadLocate_InGuildMatch = 19
  },
  _aniType = {_changeColor = 0, _changeScale = 1},
  _paneltyColor = {RED = 0, BLUE = 1},
  _ButtonString = {},
  _ButtonEvent = {},
  _resurrectionTime = 600,
  _lastUpdateTime = 0,
  _revivalTime = 600,
  _buttonAbleTime = 10,
  _buttonWaitTime = 0,
  _isButtonWaitTimeEnd = false,
  _isUseButtonAbleTime = false,
  _isObserverMode = false,
  _tempButtonAbleTimeForGuildObserver = nil,
  _startTimeForGuildObserver = nil,
  _isHasResotreExp = false,
  _isAblePvPMatchRevive = false,
  _currentDeadType = nil,
  _paneltyStringMaxCount = 10,
  _currentPaneltyStringCount = 0,
  _PaneltyColor = {},
  _PaneltyString = {},
  _isSkipDeathPenalty = false,
  _respawnButtonMaxCount = 9,
  _ButtonListByDeadType = {},
  _buttonTypeArray = nil,
  _deadCheckTime = 0,
  _deadCheckGap = 1,
  _useItem = false,
  _useFairy = false,
  _jewelKeyList = {},
  _attackerActorKeyRaw = nil,
  _canRestoreJewel = false,
  _destoryJewelCount = 0,
  _buttonTypeForRestoreJewel = nil,
  _isConsole = false,
  _initialize = false
}
runLua("UI_Data/Script/Window/DeadMessage/Panel_Window_DeadMessage_All_1.lua")
runLua("UI_Data/Script/Window/DeadMessage/Panel_Window_DeadMessage_All_2.lua")
registerEvent("FromClient_luaLoadComplete", "FromClient_DeadMessage_All_Init")
function FromClient_DeadMessage_All_Init()
  PaGlobal_DeadMessage_All:initialize()
end
